# Macros
[macros.install__arch]
    prefix = ["sudo", "pacman", "-S"]

[tasks.install-fish]
    rejects = [["which", "fish"]]
    cmds = [["@install", "fish"]]

[tasks.fish]
    deps = ["install-fish"]
    envs = [
        ["FISH_PATH", "${HM_DEST}/.config/fish"],
        ["FISHER_PATH", "${HM_DEST}/.local/share/fisherman"]
    ]
    links = [
        ["${FISH_PATH}/completions", "fish/completions"],
        ["${FISH_PATH}/functions", "fish/functions"],
        ["${FISH_PATH}/conf.d", "fish/conf.d"],
        ["${FISH_PATH}/config.fish", "fish/config.fish"],
        ["${FISHER_PATH}/fishfile", "fish/fishfile"],
    ]

[tasks.mpv]
    links = [
        ["${HM_DEST}/.config/mpv/input.conf", "mpv/input.conf"],
        ["${HM_DEST}/.config/mpv/mpv.conf", "mpv/mpv.conf"],
        ["${HM_DEST}/.config/mpv/scripts", "mpv/scripts"]
    ]

[tasks.kak]
    links = [
        ["${HM_DEST}/.config/kak/kakrc", "kak/kakrc"],
        ["${HM_DEST}/.config/kak/autoload", "kak/autoload"],
        ["${HM_DEST}/.config/kak/bin", "kak/bin"]
    ]

[tasks.default]
    deps = ["fish", "mpv"]

[tasks.full-kde]
    deps = ["default"]
