# Package managers
[macros.install__arch]
    prefix = ["sudo", "pacman", "-S"]

[macros.install__ubuntu]
    prefix = ["sudo", "apt", "install"]

[macros.install__macos]
    prefix = ["brew", "install"]

[macros.clone]
    deps = ["git"]
    prefix = ["git", "clone"]

# fish shell
[tasks.install-fish]
    rejects = [["which", "fish"]]
    cmds = [["@install", "fish"]]

[tasks.fish]
    deps = ["install-fish"]
    envs = [
        ["FISH_PATH", "${HM_DEST}/.config/fish"],
        ["FISHER_PATH", "${HM_DEST}/.local/share/fisherman"]
    ]
    links = [
        ["${FISH_PATH}/completions", "fish/completions"],
        ["${FISH_PATH}/functions", "fish/functions"],
        ["${FISH_PATH}/scripts", "fish/scripts"],
        ["${FISH_PATH}/conf.d", "fish/conf.d"],
        ["${FISH_PATH}/config.fish", "fish/config.fish"],
        ["${FISHER_PATH}/fishfile", "fish/fishfile"],
    ]

# MPV
[tasks.mpv]
    links = [
        ["${HM_DEST}/.config/mpv/input.conf", "mpv/input.conf"],
        ["${HM_DEST}/.config/mpv/mpv.conf", "mpv/mpv.conf"],
        ["${HM_DEST}/.config/mpv/scripts", "mpv/scripts"]
    ]

# Kakoune
[tasks.kak]
    links = [
        ["${HM_DEST}/.config/kak/kakrc", "kak/kakrc"],
        ["${HM_DEST}/.config/kak/autoload", "kak/autoload"],
        ["${HM_DEST}/.config/kak/bin", "kak/bin"]
    ]

# Git
[tasks.install-git]
    rejects = [["which", "git"]]
    cmds = [["@install", "git"]]

[tasks.git]
    deps = ["install-git"]
    links = [
        ["${HM_DEST}/.gitconfig", "git/gitconfig"],
        ["${HM_DEST}/.tigrc", "git/tigrc"]
    ]

# TMUX
[tasks.tmux_tpm]
    rejects = [["test", "-d", "${HM_DEST}/.tmux/plugins/tpm"]]
    deps = ["git"]
    cmds = [["@clone", "https://github.com/tmux-plugins/tpm", "${HM_DEST}/.tmux/plugins/tpm"]]

[tasks.tmux_conf]
    cmds = [
        ["mkdir", "-p", "${HM_DEST}/.tmux"],
        ["find", "${HM_SRC}/tmux",
         "-maxdepth", "1",
         "-name",  "*.tmux",
         "-exec", "ln", "-s", "{}", "${HM_DEST}/.tmux/", ";"] 
    ]
    links = [
        ["${HM_DEST}/.tmux.conf", "tmux/tmux.conf"]
    ]

[tasks.tmux]
    deps = ["tmux_conf", "tmux_tpm"]

[tasks.default]
    deps = ["fish", "kak", "git", "mpv", "tmux"]
