plug occivink/kakoune-sudo-write

# Auto-pairs
plug alexherbo2/auto-pairs.kak
hook global WinCreate .* %{ auto-pairs-enable }
map -docstring 'Toggle surround mode' global user s :auto-pairs-surround<ret>
